//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGameMarketing.Models.EntitiyFramwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scart
    {
        public int Relation_id { get; set; }
        public int Users_id { get; set; }
        public int Game_id { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Users Users { get; set; }
    }
}
